### PR TITLE
Support SDL2-CS on Tizen platform.

### PR DESCRIPTION
**Pull request by an87li**
1. Add csproj for Tizen, define constants 'TIZEN'.
2. Add conditional compilation in SDL2 for find correct library.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
At most I would only add this as a special configuration in Core.csproj, I wouldn't make a whole new project for it. More importantly, if I were to add a TIZEN def (and I wouldn't, to be honest), I would finish it and apply them to the rest of the library's native lib names.

You're going to want to look at #117 to deal with this properly.

**Comment by an87li** [comment]
Thank you for you reply~

I checked AssemblyLoadContext.LoadUnmanagedDll, it can load library in running time, But DllImport can just use a constant library name, so we need to fix the library name in compiling time but not running time.
For example, I could AssemblyLoadContext.LoadUnmanagedDll("A") and AssemblyLoadContext.LoadUnmanagedDll("B") to find the corrent library name,  and confirm "A" is the corrent library name in running time, but I can't set 'A' to DllImport.
Because in compiling time, I don't know that 'A' is the correct name, may be 'B' is the correct name.
So AssemblyLoadContext.LoadUnmanagedDll can't be a resolution for this senario.

If I add configuration in Core.csproj, then Core.csproj can just build library for Tizen ?

**Comment by flibitijibibo** [comment]
I’m not sure I understand - it sounds like it works perfectly? Can you provide sample code to show the problem?

**Comment by an87li** [comment]
No, AssemblyLoadContext.LoadUnmanagedLibrary can't work with DllImport !

string NativeLibrary;
if(AssemblyLoadContext.LoadUnmanagedDll("A") != IntPtr.Zero)
{
    // Find correct native
    NativeLibrary = "A";
}

DllImport(NativeLibrary)
publice static void SDL_FUNCTION

DllImport will build error, because NativeLibrary is not constant

**Comment by an87li** [comment]
You may test DllImport(variable) locally,  it will build error.
DllImport just can use constant string, 
like DllImport("LibSDL")
or
constant string NativeLibrary = "LibSDL";    // constant string must be fixxed in compiling time
DllImport(NativeLibrary)

**Comment by flibitijibibo** [comment]
I think you may have the use mixed up - LoadUnmanagedLibrary is called at P/Invoke time, not assembly load time - you still keep the const string as-is, but when you call, for example, SDL_Init, it’ll then call LoadUnmanagedLibrary where you can then dlopen libSDL2-2.0.so.0 when it asks for “SDL2.dll”.

**Comment by an87li** [comment]
You means DllImpoart will call LoadUnmanagedLibrary (customized) , right ?
I can't find the relationship between DllImport and AssemblyLoadContext, if you know the detail, please tell me kindly. 

I don't think DllImport will associate with customized AssemblyLoadContext.
As I know, the AssemblyLoadContext can just be customized, and be used to load library explicitly.
like AssemblyLoadContext.Load("XXXLibrary");
As for the usage of AssemblyLoadContext, please refer to [Resolving-Assemblies-in-NET-Core](https://www.codeproject.com/Articles/1194332/Resolving-Assemblies-in-NET-Core)

**Comment by flibitijibibo** [comment]
Right, once you load up the managed DLL with the custom Load(), it should use that context to resolve its own dependencies and also resolve P/Invoke dlopen calls:

https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md

**Comment by flibitijibibo** [comment]
Added info: Here's their test case:

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs#L85
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/tests/CustomTPALoadContext.cs

The Assembly return value you get doesn't really matter like it does in the test though; once it's open you can make the same references as you do now, but when it resolves the SDL2 types it'll go to that Assembly you loaded to resolve the type.

**Pull request closed without merging**
