### PR TITLE
Made wrapper work against CoreCLR

### PR DESCRIPTION
**Pull request by manu-st**
The main changes in the code are the manual marshalling of the UTF8 strings to .NET String.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
I'm not really sure I want any of this. On top of immediately breaking compatibility with previous versions (big problem for projects like FNA), both in the project _and_ the source, I really don't want any of this additional glitter that links to your repos, sources, etc. Particularly the UTF8String - what's the difference and why should I care? Same story for the struct marshaling; what am I looking at and why is it worth breaking compatibility, assuming CoreCLR is not compatible with the current marshaling?

If this works with your project and with CoreCLR, great, but without an explanation as to why it should be okay that it works with nothing else, I can't even recommend this as a branch for when CoreCLR actually ships.

**Comment by manu-silicon** [comment]
The main thing that you is really problematic in my view is the lack of System.RuntimeArgumentHandle in CoreCLR which removes of the Logging methods. I do not have a solution for those yet.

As for the rest, it should work for both traditional .NET and CoreCLR. I don't see where I broke backward compatibility, the APIs are the same.

For struct marshalling, what I read is that it seems to be useless now, if really this is required for the traditional .NET framework, we can add some #if to preserve the old struct marshalling.

**Comment by flibitijibibo** [comment]
Here is the result when I use xbuild on my machine locally:

```
[flibitijibibo@flibitTower SDL2-CS]$ xbuild 
XBuild Engine Version 2.10.8.0
Mono, Version 2.10.8.0
Copyright (C) Marek Sieradzki 2005-2008, Novell 2008-2011.

Build started 10/18/2015 8:43:14 PM.
__________________________________________________
/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.csproj:  warning : Could not find project file /home/flibitijibibo/Programming/csLibraries/test/SDL2-CS//CoreFX/configs/CoreCLR.CSharp.targets, to import. Ignoring.
Project "/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Debug|Any CPU".
	Target Build:
		Project "/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.csproj" (default target(s)):
/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.csproj: error : Target named 'Build' not found in the project.
		Done building project "/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.sln".-- FAILED
Done building project "/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.sln".-- FAILED

Build FAILED.

Warnings:

/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.csproj:  warning : Could not find project file /home/flibitijibibo/Programming/csLibraries/test/SDL2-CS//CoreFX/configs/CoreCLR.CSharp.targets, to import. Ignoring.

Errors:

/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.sln (default targets) ->
(Build target) ->
/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.csproj (default targets) ->

	/home/flibitijibibo/Programming/csLibraries/test/SDL2-CS/SDL2-CS.csproj: error : Target named 'Build' not found in the project.

	 1 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:00.1032020
```

And the Makefile:
```
[flibitijibibo@flibitTower SDL2-CS]$ make
rm -rf bin/debug
mkdir -p bin/debug
cp SDL2-CS.dll.config bin/debug
dmcs /unsafe -debug -out:bin/debug/SDL2-CS.dll -target:library src/LPUtf8StrMarshaler.cs src/SDL2.cs src/SDL2_image.cs src/SDL2_mixer.cs src/SDL2_ttf.cs
error CS2001: Source file `src/LPUtf8StrMarshaler.cs' could not be found
Compilation failed: 1 error(s), 0 warnings
Makefile:15: recipe for target 'debug' failed
make: *** [debug] Error 1
```

That last one's not too fair, so I updated the Makefile for you. The result:

```
[flibitijibibo@flibitTower SDL2-CS]$ make
rm -rf bin/debug
mkdir -p bin/debug
cp SDL2-CS.dll.config bin/debug
dmcs /unsafe -debug -out:bin/debug/SDL2-CS.dll -target:library src/UTF8String.cs src/SDL2.cs src/SDL2_image.cs src/SDL2_mixer.cs src/SDL2_ttf.cs
src/UTF8String.cs(118,67): error CS1501: No overload for method `GetString' takes `2' arguments
/usr/lib/mono/4.0/mscorlib.dll (Location of the symbol related to previous error)
src/SDL2.cs(799,81): error CS0308: The non-generic method `System.Runtime.InteropServices.Marshal.SizeOf(object)' cannot be used with the type arguments
/usr/lib/mono/4.0/mscorlib.dll (Location of the symbol related to previous error)
src/SDL2.cs(799,60): error CS1502: The best overloaded method match for `System.Runtime.InteropServices.Marshal.AllocHGlobal(System.IntPtr)' has some invalid arguments
/usr/lib/mono/4.0/mscorlib.dll (Location of the symbol related to previous error)
src/SDL2.cs(799,60): error CS1503: Argument `#1' cannot convert `object' expression to type `System.IntPtr'
src/SDL2.cs(2849,53): error CS0308: The non-generic method `System.Runtime.InteropServices.Marshal.PtrToStructure(System.IntPtr, object)' cannot be used with the type arguments
/usr/lib/mono/4.0/mscorlib.dll (Location of the symbol related to previous error)
src/SDL2.cs(5533,54): error CS0308: The non-generic method `System.Runtime.InteropServices.Marshal.PtrToStructure(System.IntPtr, object)' cannot be used with the type arguments
/usr/lib/mono/4.0/mscorlib.dll (Location of the symbol related to previous error)
src/SDL2_image.cs(77,56): error CS0308: The non-generic method `System.Runtime.InteropServices.Marshal.PtrToStructure(System.IntPtr, object)' cannot be used with the type arguments
/usr/lib/mono/4.0/mscorlib.dll (Location of the symbol related to previous error)
src/SDL2_mixer.cs(144,56): error CS0308: The non-generic method `System.Runtime.InteropServices.Marshal.PtrToStructure(System.IntPtr, object)' cannot be used with the type arguments
/usr/lib/mono/4.0/mscorlib.dll (Location of the symbol related to previous error)
src/SDL2_ttf.cs(82,56): error CS0308: The non-generic method `System.Runtime.InteropServices.Marshal.PtrToStructure(System.IntPtr, object)' cannot be used with the type arguments
/usr/lib/mono/4.0/mscorlib.dll (Location of the symbol related to previous error)
Compilation failed: 9 error(s), 0 warnings
Makefile:15: recipe for target 'debug' failed
make: *** [debug] Error 1
```

**Comment by manu-silicon** [comment]
Thanks for the output. I've been compiling against .NET 4.5/4.6 and thus used the most recent versions of the APIs. The error you are getting are due to this. What is the minimum .NET Framework that you are targeting?

**Comment by flibitijibibo** [comment]
The baseline for FNA's C# wrappers is .NET 4.0, since that's where XNA4 sits. So it's not too far back, but enough to fuss with 4.5/4.6... I've been fighting those issues on my end as well:

https://github.com/flibitijibibo/FNA/commit/ba19889d9601413d034119e5c46daa772fe59bd9

**Comment by manu-silicon** [comment]
I've update the code so that it compiles against .NET 4.0.

**Comment by flibitijibibo** [comment]
Cool, this builds with the edited Makefile. I'm still not sure about the project file changes and the Marshaler replacement, but since CoreCLR is a WIP anyway I'll just keep this pull request here to track the changes made in your branch to support it. Once it's actually out and we know what we can and can't support on the various targets we have to care about we can start merging this for real.

Here's hoping Microsoft stays on schedule.

**Comment by manu-silicon** [comment]
No problem. The changes in the project file changes can be ignored for the moment, what is important is the code! On my end, I'll keep my work in sync with your master branch.

**Comment by benpye** [comment]
I have updated @manu-silicon 's branch to be mergeable with the current tree, and converted to the new xproj format. This should now build both a portable dotnet version as well as a net40 version. I see nothing stopping other targets being added either. This can then be used to produce a NuGet package which can be consumed by either net40 or a dotnet compatible project. See https://github.com/benpye/SDL2-CS/tree/net-core

**Comment by flibitijibibo** [comment]
Can someone explain to me how they turned 2 project files into 4 files including raw JSON files that are all randomly interleaved...? And where did the source file listing go? Also I think that .user file is an extraneous file... and does it require that the folder be named SDL2-CS/ rather than src/? Why?

Why everything?

**Comment by benpye** [comment]
Oops, yeah, the .user was certainly in error. The source file listing has been replaced by include/exclude lists but it defaults to everything in the directory. The directory had to be renamed as it seems that your binaries end up being named after their directory (there is quite possibly a way to fix this). The only required file really is project.json, if you didn't want VS then nothing else would be required, and you could use just project.json with the dotnet command line. However, to get integration you do require the .sln still in addition to the .xproj and global.json . It's probably not a great idea to merge this directly anyway, though what should be possible is to have both types of project in the tree, at least until the dotnet cli hits 1.0.

**Comment by benpye** [comment]
That said, you don't have to got this far to target the new platform, but it's the only way to do multitargeting. The alternative is https://github.com/benpye/SDL2-CS/tree/3c2bfdd51de4810bd6a03689cf634dd4bcc55255 . Still requires project.json but is otherwise more similar to what already exists.

**Comment by flibitijibibo** [comment]
Fair enough, I guess... the baseline for this getting merged into mainline is that it must achieve the following:

- It must have _zero_ effects on the current .NET4 project and must be 100% compatible with _zero_ performance hits or ifdef soup. .NET4 is the XP of .NET and that's Microsoft's own fault, so we get to live with it too.
- The project system must be as simple as a single command. The Makefile uses `make`, the sln/csproj use `xbuild`. If the new system creates more files than the csproj/sln or requires more than typing a single line in a shell, it is crap and is not going in anything I maintain. That'll be for Microsoft's interns to figure out how to not ruin their own build system, it will not be my problem.
- It must be compatible with FNA out of the box with zero modifications to FNA (see above).

If we can nail those down and get CoreCLR happy, great. If not, CoreCLR will have completely missed the point of creating a FOSS'd .NET ecosystem and will not be worth dealing with as a maintainer of existing code that ships in WAY too many large-scale commercial projects. If it can't even beat Mono, that'll be a sad moment for sure.

**Comment by flibitijibibo** [comment]
Also, if it simplifies the problem at all, SDL2# is never getting NuGet packages from me. So you can strip that stuff out if it helps.

**Comment by benpye** [comment]
I know you said you're opposed to #if's, what would your opinion be if these were to disable functionality on .NET Core. As mentioned before `__arglist` is no longer supported. One solution may be to implement vsnprintf in C#, however this still causes issues with the error methods. Obviously it'd be easy to use a C# style format string but that's going to break backward compatibility.

**Comment by flibitijibibo** [comment]
Do they have a stated reason as to why it's missing from Core?

**Comment by benpye** [comment]
Sorry slight mistake on my part. __arglist may actually be present but
because CustomMarshaller is no longer supported (apparently as MCG cannot
handle it), we have to wrap all the methods with strings. I don't think we
can wrap an __arglist function, though I'd happily be proven wrong. We are
missing RuntimeArgumentHandle however.

**Comment by flibitijibibo** [comment]
Ah, so we're still stuck with the UTF8String problem then.

Seems a little odd that they can't support their own language, so this may be stuck on a `coreclr` branch or something until they can remember how to do that.

**Comment by manu-silicon** [comment]
Personally I'm not a big fan of custom marshaler as I prefer to show how those conversion are actually done. A little bit more of typing but not much.

As for the #ifdef it might be difficult to remove them as pointed by @benpye some classes are missing from CoreCLR/CoreFX. I consider this more blocking than the UTF8String issue. The question I had when I see them if this is really something consumers of the SDL library are actively using. Usually when you write an application, you use your own way to log/report warnings/errors.

**Comment by flibitijibibo** [comment]
On top of being used by the application it's also used by SDL itself, so it's helpful when debugging the library - per the header file:

https://hg.libsdl.org/SDL/file/c59a7e780093/include/SDL_log.h

**Comment by manu-silicon** [comment]
@flibitijibibo Yes, when you want to debug the library, but most users won't do that.

**Comment by flibitijibibo** [comment]
As the GitHub thread now points out, this was recently brought up by an FNA issue (https://github.com/FNA-XNA/FNA/issues/34). I just wanted to check up on how CoreCLR was doing with SDL2#... has the marshaling support improved at all? The need for such a workaround still gives me a headache. :(

**Comment by manu-silicon** [comment]
@flibitijibibo CoreCLR has now a UTF8 marshaller (see https://github.com/dotnet/coreclr/pull/4793) so we could try to use it when targeting CoreCLR. However the change to build against PCL is the reason now why we cannot use CustomMarshaler.

PS: Seems that CoreCLR also has CustomMarshaler too now, but I haven't been able to verify that yet.

**Comment by xgalaxy** [comment]
__arglist, RuntimeArgumentHandle, and friends are not coming in .NET Core. The solution they use in CoreFx for this is to declare overloads for each of the specific arguments they use. See [Interop.PrintF](https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/System.Native/Interop.PrintF.cs) as an example.

Seems like a pain in the ass.. but if you want to keep the Log functionality around you will have to create the overloads, limit it to supporting up to X number of args, or wrap the calls and string format yourself and pass it the already formatted string.

**Comment by flibitijibibo** [comment]
I'll probably just def it out until Microsoft can implement Microsoft C# from 2006 for Microsoft .NET Core from 2016. It's not used in FNA so for the moment I'm not too heartbroken about it...

**Comment by wzb0313** [comment]
.NET Core v1.1.0-preview1 added new UnmanagedType **UnmanagedType.LPUTF8Str** into System.Runtime.InteropServices. 

Can this issue be solved by using the LPUTF8Str Marshaller? 

```csharp 
namespace System.Runtime.InteropServices {
     public static class Marshal {
+        public static string PtrToStringUTF8(IntPtr ptr);
+        public static string PtrToStringUTF8(IntPtr ptr, int byteLen);
+        public static IntPtr StringToCoTaskMemUTF8(string s);
+        public static void ZeroFreeCoTaskMemUTF8(IntPtr s);
     }
     public enum UnmanagedType {
+        LPUTF8Str = 48,
     }
 }
```
see [1.0-1.1-api-diff System.Runtime.InteropServices.md](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.0-1.1-api-diff/1.0-1.1-api-diff_System.Runtime.InteropServices.md)

**Comment by LennardF1989** [comment]
Few months later, how are things looking with .NET Core right now? Is there a future for SDL2-CS in it and implicitly FNA, or still far far away? Would love to see Mono go as well...

**Comment by rafaelvasco** [comment]
I'd like too see this .net core port too. This SDL2 binding is the only complete one in the Internet. There's another (https://github.com/mellinoe/Veldrid.SDL2) that is made for .NET Core but it's incomplete. Since it appears .NET Core is the future of crossplatform .NET , supporting .NET Core is essential if one aims for multiplatform support.

**Comment by flibitijibibo** [comment]
It appears .NET Standard 2.0 will be bringing back CustomMarshaler, and at the same time, it _still_ isn't bringing LPUTF8Str, so it looks like all the changes regarding string marshaling can be undone. I'm not entirely sure why LPUTF8Str does not appear in _any_ .NET version despite having been in the project sources for about a year, but either way I'd be taking the .NET4 compatibility route.

What I'm not sure about is __arglist, but if we have to make an `#if NETSTANDARD` for those calls then that'll have to be that.

It also appears that they're back on msbuild .csproj files instead of that weird JSON mess, so that's fixed too.

So, the TODO:

- [ ] Create SDL2-CS.Core.csproj
- [ ] `#if !NETSTANDARD` for `__arglist` calls

Is there anything else left to make this compatible?

**Comment by LennardF1989** [comment]
Seems to be complete, other than also getting the ICustomMarshaler in there (https://github.com/dotnet/coreclr/commit/e8c4f5499136e137fdb3e3c5fb798b2637b21996) - can confirm that VS2017 with DNC 2.0 uses a .csproj now, where it has an appsettings.json on the side for actual runtime configuration. There is however still the launchsettings.json under Properties, but I think that's relevant for Class Libraries, since it's all about launching IIS Express and the like.

**Comment by flibitijibibo** [comment]
Yeah, let's do a separate sln/csproj for Core. If someone can send those 2 files over once they're ready I can merge them in and we can finally call this done; I'm not too worried about pre-2.0 since Core/UWP minimum requirements can be a lot more aggressive than .NET Framework requirements.

**Comment by clarvalon** [comment]
I spent a bit of time this evening prototyping a dotnet core solution for my game engine, using a net standard 2.0 version of FNA.  Pretty pleased with the results so far:  https://twitter.com/Clarvalon/status/917541809039003648

A few temporary workarounds I had to implement:

* Relative files weren't loading correctly without the following inserted at the beginning: 

  `Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location));`

  See:  https://github.com/dotnet/project-system/issues/2239

* Resources.GetResource() was not finding the embedded effects as GetManifestResourceStream was not finding the stream.  For some reason the results from GetManifestResourceNames were based on file path rather than namespace.

* I couldn't get it to work with the windows x86 native DLLs, only had success with x64.

The above may be due to my lack of knowledge about dotnet core more than anything.

**Comment by LennardF1989** [comment]
@clarvalon Cool stuff, thanks for sharing. I'll see how my FNA project reacts to dotnet core somewhere this week. I'll use this oppertunity to also provide proper sln/sproj files.

Any chance you can share the ones you have now for FNA and dependencies through Gists?

**Comment by flibitijibibo** [comment]
Yeah if you guys want to do FNA sln/csproj files at the same time I'd be up for that too, though I wonder if those can be used in UWP solutions... would be cool if the Core project was our Xbone project too.

Regarding those embedded resources, I bet the Core project needs LogicalName properties like we do in the current project:

https://github.com/FNA-XNA/FNA/blob/master/FNA.csproj#L413

No idea about Win32 though, I didn't even know CoreCLR had official 32-bit support.

**Comment by clarvalon** [comment]
Thanks Ethan - spot on about the LogicalName properties.  As soon as I added these the GetResource() issue went away.

@LennardF1989 Here's the updated .csproj:  https://gist.github.com/clarvalon/98546b9fbcbc1d03f68f4c1e14e52aae

One thing to be aware of is that Core projects will include most items by default, with the ability to exclude items (on the basis that this will lead to cleaner .csproj files).  I prefer the old way i.e. explicitly include items, so reverted to old behaviour using the following

`	<PropertyGroup>
		<EnableDefaultItems>false</EnableDefaultItems>
	</PropertyGroup>
`

My .sln isn't standalone and uses some non-standard preprocessor symbols so not sure it would be much use to anyone.  It's just a core 2.0 console app.

Pretty sure that x86 is supported as one of the publish runtime options is 'win-x86'.  I'll take a look at this when I'm feeling more awake.  I'm probably just overlooking something obvious.

As an aside, UWP support for NET Standard 2.0 has [just been announced](https://blogs.msdn.microsoft.com/visualstudio/2017/10/10/visual-studio-2017-version-15-4-released/) for Visual Studio 2017 15.4.  Good timing!

**Comment by flibitijibibo** [comment]
Oh neat, if we can disable the global Include behavior that’d be nice - cool as it is to keep the project file small, in some cases like FNA where we statically link it’s actually more accurate to the Framework project to exclude a handful of files.

If someone tries put SDL with UWP C#, let me know how it goes - SDL_main is my biggest concern and I have no idea how to get around all that XAML trash on the C# side.

**Comment by flibitijibibo** [comment]
Quick update: I've added SDL_WinRTRunApp to SDL2#:

https://github.com/flibitijibibo/SDL2-CS/commit/689dcf53424d95806aea73c7ce83961cda30d438

If what I'm thinking is possible, all we should have to do to get SDL working with UWP is to take a C# project, strip out _all_ of the code, and replace it with our usual Main function, with a slight change:

```
[STAThread]
static void Main(string[] args)
#if UWP
{
    SDL.SDL_WinRT_mainFunction main = FakeMain;
    SDL.SDL_WinRTRunApp(main, IntPtr.Zero);
}

static int FakeMain(int argc, IntPtr[] argv)
{
    // WinRT doesn't give us args :(
    RealMain(new string[0]);
}

static void RealMain(string[] args)
#endif
{
    // blah...
}
```

This should avoid us having to have XAML wrapping on the C# side, and it also fulfills what SDLmain does on the C/C++ side:

https://hg.libsdl.org/SDL/file/b5e404b928ea/src/main/winrt/SDL_winrt_main_NonXAML.cpp

Dunno if we need that `Windows::Foundation::Initialize` function for C# though.

**Comment by flibitijibibo** [comment]
One more update: James at Bit Kit Games graciously sent me an Xbone so I can target UWP locally. I now have a setup with which I can test any of your patches for this, but note that as of writing it appears even the Fall Update preview for Xbone does not appear to accept applications requiring 10.0.16299. I tested this with 1710.171012-1520 and it still needs to target 1 version lower for it to work.

If someone gets the official update before I do, definitely test App1 against it and see if we can target it, if we can't then this may have to wait a little while longer...

**Comment by flibitijibibo** [comment]
I just added a project file to compile SDL2# against .NET Standard 2.0:

https://github.com/flibitijibibo/SDL2-CS/commit/11adade8c29d6ea8a91f7754dd25e8297694b2a0

With this, the issue is now closed. However, I'm adding an issue to track UWP support, since I still can't get this Xbone to run anything C#-related with the Fall Creator's Update minimum requirement:

https://github.com/flibitijibibo/SDL2-CS/issues/114

**Pull request closed without merging**
