### PR TITLE
net core quickstart example

### PR DESCRIPTION
**Pull request by devel0**
samples-core folder with netcore examples ready to run
just enter then issue `dotnet run`

notes:
- libsdl2-2.0.0 must installed ( ie. `apt-get install -y libsdl2-2.0.0` )

a convenient `.vscode` folder included to allow open the project into vscode and start debugging

### CODE REVIEW

**Comment by flibitijibibo** [comment]
This sample looks good! I would host these separately though, this repository is meant to be pretty bare bones. If a larger set of samples was made I’d be up for linking it as a third-party repo in the README.

**Comment by devel0** [comment]
It's ok.
actually I was wondering which nuget packages correspond to the SDL2-CS.Core.csproj, infact if I use a test project adding nuget package from [here](https://www.nuget.org/packages/SDL2-CS.NetCore/) I got problem about locating dll because that package not includs .config file with dll maps, while if I copy SDL2-CS.dll and SDL2-CS.dll.config that your makefile produces everything works correctly.
Note that mentioned nuget package comes from a [fork](https://github.com/IntelOrca/SDL2-CS) so I ask you if there is a nuget package for SDL2-CS.Core related to your repository ?
If you actually not provide one a really simple method to build package is explained with this [script](https://github.com/devel0/netcore-util/blob/master/publish.sh) and information picked directly from [csproj](https://github.com/devel0/netcore-util/blob/master/netcore-util/netcore-util.csproj).

**Comment by flibitijibibo** [comment]
We do not provide any NuGet packages and never will. If I were writing the samples I would reference the source directly instead of using premade packages.

**Comment by devel0** [comment]
Thanks for clarification,

**Pull request closed without merging**
